### ISSUE TITLE
will not login

### ISSUE THREAD

**Issue by zany130** [korapp/plasma-inoreader#3]
followed the instructions and added appId and appKey to the plasmoid config and login with my account, and it just does nothing saying no user is logged in 

Operating System: Garuda Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.8-272-tkg-bmq (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Comment by korapp** [comment]
Is it your first try of the widget or did you have v0.1.0 installed before?
Does it behave differently after re-login or restarting Plasma (`plasmashell --replace`)?
Is KDE Wallet active?

**Comment by zany130** [comment]
I did have a earlier version but I uninstalled it since it was giving me the same issue. Logging in and out doesn't seem to make a difference nor does restarting plasma shell

KDE wallet is enabled and it does seem like its saving something there?
![image](https://user-images.githubusercontent.com/25832539/202047502-eb55ad5c-c146-403f-bf42-1ec5afdebd24.png)

**Comment by zany130** [comment]
Was able to get it working by deleting that folder then uninstalling the applet, restarting kde, then reinstalling the applet
